name: ui_project_hochiminh_museum
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ">=3.1.2 <4.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^4.4.2

  #Icons
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.2

  # State Management
  get: ^4.6.6
  get_storage: ^2.1.1

  # Utility Packages
  http: ^1.1.0
  logger: ^2.0.2+1
  url_launcher: ^6.2.1
  flutter_native_splash: ^2.3.6
  smooth_page_indicator: ^1.1.0

  # Product Specific
  readmore: ^2.2.0
  carousel_slider: ^4.2.1
  flutter_rating_bar: ^4.0.1
  capped_progress_indicator: ^0.0.2
  keyboard_dismisser: ^3.0.0
  intl: ^0.18.1
  cached_network_image: ^3.3.0
  photo_view: ^0.14.0
  hoverover: ^0.1.1
  video_player: ^2.8.1
  flutter_video_view: ^2.0.2+1
  flick_video_player: ^0.5.0
  youtube_player_flutter: ^8.1.2
  auto_orientation: ^2.3.1
  uuid: ^4.2.1
  firebase_core: ^2.22.0
  firebase_auth: ^4.14.0
  cloud_firestore: ^4.13.1
  firebase_storage: ^11.5.1
  image_picker: ^1.0.4
  transparent_image: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/on_boarding_images/
    - assets/logos/
    - assets/icons/brands/
    - assets/images/animations/
    - assets/images/news/
    - assets/images/illustrations/
    - assets/images/banners/
    - assets/images/products/
    - assets/images/content/
    - assets/images/indoor_map/
    - assets/json/indoor_map/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800
    - family: OpenSans
      fonts:
        - asset: assets/fonts/open_sans/OpenSans_Condensed-Light.ttf
          weight: 300
        - asset: assets/fonts/open_sans/OpenSans_Condensed-Regular.ttf
          weight: 400
        - asset: assets/fonts/open_sans/OpenSans_Condensed-Medium.ttf
          weight: 500
        - asset: assets/fonts/open_sans/OpenSans_Condensed-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/open_sans/OpenSans_Condensed-Bold.ttf
          weight: 700
        - asset: assets/fonts/open_sans/OpenSans_Condensed-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/open_sans/OpenSans_SemiCondensed-Light.ttf
          weight: 300
        - asset: assets/fonts/open_sans/OpenSans_SemiCondensed-Regular.ttf
          weight: 400
        - asset: assets/fonts/open_sans/OpenSans_SemiCondensed-Medium.ttf
          weight: 500
        - asset: assets/fonts/open_sans/OpenSans_SemiCondensed-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/open_sans/OpenSans_SemiCondensed-Bold.ttf
          weight: 700
        - asset: assets/fonts/open_sans/OpenSans_SemiCondensed-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/open_sans/OpenSans-Light.ttf
          weight: 300
        - asset: assets/fonts/open_sans/OpenSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/open_sans/OpenSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/open_sans/OpenSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/open_sans/OpenSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/open_sans/OpenSans-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/open_sans/OpenSans_Condensed-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/open_sans/OpenSans_Condensed-Italic.ttf
          style: italic
        - asset: assets/fonts/open_sans/OpenSans_Condensed-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/open_sans/OpenSans_Condensed-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/open_sans/OpenSans_Condensed-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/open_sans/OpenSans_Condensed-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/open_sans/OpenSans_SemiCondensed-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/open_sans/OpenSans_SemiCondensed-Italic.ttf
          style: italic
        - asset: assets/fonts/open_sans/OpenSans_SemiCondensed-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/open_sans/OpenSans_SemiCondensed-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/open_sans/OpenSans_SemiCondensed-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/open_sans/OpenSans_SemiCondensed-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/open_sans/OpenSans-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/open_sans/OpenSans-Italic.ttf
          style: italic
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
